name: 'Releases Changelog'
description: 'Creates changelog based on all releases.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
