
name: Labels

on:
  push:
    tags-ignore:
    - '*'
    paths:
    - .github/labels.yml

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: Sync
      uses: micnncim/action-label-syncer@v1
